sudo: false

dist: xenial

branches:
  only:
    - master

# Install doxygen
addons:
  apt:
    packages:
      - doxygen

# Build API reference
script:
  - cd gst-libs/gst/videoanalytics
  - doxygen Doxyfile

# Deploy API reference
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: gst-libs/gst/videoanalytics/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
